In [1]:
# Formação Cientista de Dados - Fernando Amaral e Jones Granatyr
# Amostragem Simples

In [2]:
# Importação das bibliotecas: pandas para carregar arquivos .csv e numpy para gerar números aleatórios
import numpy as np
import pandas as pd

In [3]:
# Carregamento da base de dados (o arquivo .csv precisa estar na mesma pasta do código fonte) e visualização dos dados
base = pd.read_csv('../dados/iris.csv')
base

     sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
# Verificar quantas linhas e colunas existem na base de dados, 150 linhas e 5 colunas
base.shape

(150, 5)

In [12]:
base.groupby('class').sum()

                 sepal length  sepal width  petal length  petal width
class
Iris-setosa             250.3        170.9          73.2         12.2
Iris-versicolor         296.8        138.5         213.0         66.3
Iris-virginica          329.4        148.7         277.6        101.3

In [5]:
# Mudança da semente aleatória randômica para manter os resultados em várias execuções
np.random.seed(2345)
# 150 amostras, de 0 a 1, com reposição, probabilidades equivalentes
amostra = np.random.choice(a=[0, 1], size=150, p=[0.7, 0.3])
# Verificar tamanho da amostra
# len(amostra)
# Verificar tamanho da amostra para valores igual a 1 e 0
# len(amostra[amostra == 1])
# len(amostra[amostra == 0])
amostra

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [6]:
base_final = base.loc[amostra == 0]
base_final.shape

(101, 5)

In [7]:
base_final2 = base.loc[amostra == 1]
base_final2.shape

(49, 5)